# Generated by Django 5.0.14 on 2026-07-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCadastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(max_length=30, verbose_name='Estado Civil')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone Residencial')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('profissao', models.CharField(max_length=80, verbose_name='Profissão')),
                ('empresa', models.CharField(max_length=120, verbose_name='Empresa')),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Mensal R$')),
                ('tempo_emprego', models.CharField(blank=True, max_length=40, verbose_name='Tempo de Emprego')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua / Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('tempo_residencia', models.CharField(blank=True, max_length=40, verbose_name='Tempo de Residência')),
                ('imovel_endereco', models.CharField(max_length=200, verbose_name='Endereço do Imóvel Pretendido')),
                ('imovel_proprietario', models.CharField(max_length=120, verbose_name='Proprietário do Imóvel')),
                ('imovel_aluguel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Aluguel R$')),
                ('imovel_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Condomínio R$')),
                ('imovel_iptu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do IPTU R$')),
                ('imovel_residentes', models.PositiveIntegerField(verbose_name='Número de Residentes')),
                ('garantia_tipo', models.CharField(max_length=40, verbose_name='Tipo de Garantia')),
                ('ref1_nome', models.CharField(blank=True, max_length=120, verbose_name='Referência 1 - Nome')),
                ('ref1_telefone', models.CharField(blank=True, max_length=20, verbose_name='Referência 1 - Telefone')),
                ('ref2_nome', models.CharField(blank=True, max_length=120, verbose_name='Referência 2 - Nome')),
                ('ref2_telefone', models.CharField(blank=True, max_length=20, verbose_name='Referência 2 - Telefone')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('lgpd_consent', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ficha Cadastral',
                'verbose_name_plural': 'Fichas Cadastrais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
