# Generated by Django 5.0.14 on 2026-07-16 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacadastral',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AddField(
            model_name='fichacadastral',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='fichacadastral',
            name='status',
            field=models.CharField(choices=[('novo', 'Cadastro Novo'), ('analise', 'Em Análise'), ('consultado', 'Consultado'), ('pago', 'Pago')], default='novo', max_length=20, verbose_name='Status'),
        ),
    ]
