# Generated by Django 5.0.14 on 2026-07-16 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_fichacadastral_modificado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichacadastral',
            name='garantia_tipo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo de Garantia'),
        ),
        migrations.AlterField(
            model_name='fichacadastral',
            name='imovel_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Aluguel R$'),
        ),
        migrations.AlterField(
            model_name='fichacadastral',
            name='imovel_endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço do Imóvel Pretendido'),
        ),
        migrations.AlterField(
            model_name='fichacadastral',
            name='imovel_proprietario',
            field=models.CharField(blank=True, max_length=120, verbose_name='Proprietário do Imóvel'),
        ),
        migrations.AlterField(
            model_name='fichacadastral',
            name='imovel_residentes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Residentes'),
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=250, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
